{
	"filelist":[
      		"/js/json2/json2.min.js",
		"/js/jquery/3.3.1/jquery.min.js",
		"/js/jqueryui/1.12.1/jquery-ui.min.js",
		"/js/react/react.min.js",
		"/js/react/react-dom.min.js",
		"/js/react/react-cookie.0.4.9.min.js",
		"/js/react/ReactRouter/3.0.2/ReactRouter.min.js",
		"/js/ReactPlugin.js",
		"/css/Bootstrap/v4.1.3/bootstrap.min.js",
		"/css/Bootstrap/v4.1.3/popper.min.js"
	]
}
