{
	"filelist":[
      		"/js/json2/json2.min.js",
		"/js/react/react.min.js",
		"/js/react/react-dom.min.js",
		"/js/react/react-cookie.0.4.9.min.js",
		"/js/react/ReactRouter/3.0.2/ReactRouter.min.js",
		"/js/ReactPlugin.js"
	]
}
